/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSharedGoalsRouteImport } from './routes/_app/shared-goals'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOrgRouteImport } from './routes/_app/org'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppEscalationsRouteImport } from './routes/_app/escalations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCyclesRouteImport } from './routes/_app/cycles'
import { Route as AppCheckinsRouteImport } from './routes/_app/checkins'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppManagerDashboardRouteImport } from './routes/_app/manager.dashboard'
import { Route as AppEmployeeDashboardRouteImport } from './routes/_app/employee.dashboard'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedGoalsRoute = AppSharedGoalsRouteImport.update({
  id: '/shared-goals',
  path: '/shared-goals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalationsRoute = AppEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCyclesRoute = AppCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinsRoute = AppCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerDashboardRoute = AppManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeDashboardRoute = AppEmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/checkins': typeof AppCheckinsRoute
  '/cycles': typeof AppCyclesRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/goals': typeof AppGoalsRoute
  '/org': typeof AppOrgRoute
  '/profile': typeof AppProfileRoute
  '/shared-goals': typeof AppSharedGoalsRoute
  '/team': typeof AppTeamRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/employee/dashboard': typeof AppEmployeeDashboardRoute
  '/manager/dashboard': typeof AppManagerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/checkins': typeof AppCheckinsRoute
  '/cycles': typeof AppCyclesRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/goals': typeof AppGoalsRoute
  '/org': typeof AppOrgRoute
  '/profile': typeof AppProfileRoute
  '/shared-goals': typeof AppSharedGoalsRoute
  '/team': typeof AppTeamRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/employee/dashboard': typeof AppEmployeeDashboardRoute
  '/manager/dashboard': typeof AppManagerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/checkins': typeof AppCheckinsRoute
  '/_app/cycles': typeof AppCyclesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escalations': typeof AppEscalationsRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/org': typeof AppOrgRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/shared-goals': typeof AppSharedGoalsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/employee/dashboard': typeof AppEmployeeDashboardRoute
  '/_app/manager/dashboard': typeof AppManagerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/checkins'
    | '/cycles'
    | '/dashboard'
    | '/escalations'
    | '/goals'
    | '/org'
    | '/profile'
    | '/shared-goals'
    | '/team'
    | '/admin/dashboard'
    | '/employee/dashboard'
    | '/manager/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/checkins'
    | '/cycles'
    | '/dashboard'
    | '/escalations'
    | '/goals'
    | '/org'
    | '/profile'
    | '/shared-goals'
    | '/team'
    | '/admin/dashboard'
    | '/employee/dashboard'
    | '/manager/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/analytics'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/checkins'
    | '/_app/cycles'
    | '/_app/dashboard'
    | '/_app/escalations'
    | '/_app/goals'
    | '/_app/org'
    | '/_app/profile'
    | '/_app/shared-goals'
    | '/_app/team'
    | '/_app/admin/dashboard'
    | '/_app/employee/dashboard'
    | '/_app/manager/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared-goals': {
      id: '/_app/shared-goals'
      path: '/shared-goals'
      fullPath: '/shared-goals'
      preLoaderRoute: typeof AppSharedGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org': {
      id: '/_app/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalations': {
      id: '/_app/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof AppEscalationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cycles': {
      id: '/_app/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof AppCyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkins': {
      id: '/_app/checkins'
      path: '/checkins'
      fullPath: '/checkins'
      preLoaderRoute: typeof AppCheckinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/dashboard': {
      id: '/_app/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AppManagerDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee/dashboard': {
      id: '/_app/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof AppEmployeeDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCheckinsRoute: typeof AppCheckinsRoute
  AppCyclesRoute: typeof AppCyclesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscalationsRoute: typeof AppEscalationsRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppOrgRoute: typeof AppOrgRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSharedGoalsRoute: typeof AppSharedGoalsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppEmployeeDashboardRoute: typeof AppEmployeeDashboardRoute
  AppManagerDashboardRoute: typeof AppManagerDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCheckinsRoute: AppCheckinsRoute,
  AppCyclesRoute: AppCyclesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscalationsRoute: AppEscalationsRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppOrgRoute: AppOrgRoute,
  AppProfileRoute: AppProfileRoute,
  AppSharedGoalsRoute: AppSharedGoalsRoute,
  AppTeamRoute: AppTeamRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppEmployeeDashboardRoute: AppEmployeeDashboardRoute,
  AppManagerDashboardRoute: AppManagerDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
